spring.application.name=LamNexus


spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.chat.options.model=openai/gpt-oss-20b:free

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

logging.level.org.springframework.ai=DEBUG
logging.level.com.openai=DEBUG